/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "servidor_registro.h"

bool_t
registrar_accion_1_svc(nombre arg1, accion arg2, fichero arg3, void *result,  struct svc_req *rqstp)
{
	bool_t retval;

	if (arg3 != NULL && strlen(arg3) > 0) {
		printf("%s\n%s %s\n", arg1, arg2, arg3);
	} else {
		printf("%s\n%s\n", arg1, arg2);
	}

	retval = TRUE;

	return retval;
}

int
programa_registro_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
